server {
    listen 80;
    server_name localhost;

    # Configuração para servir os arquivos estáticos do Frontend SPA
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # Storage Estático Local Definitivo (Custo Zero e Desempenho Sênior)
    # Permite baixar as imagens WebP processadas pelo Worker diretamente do volume
    location /assets/ {
        alias /app/armazenamento_definitivo/;
        autoindex off;
        expires 30d;
        add_header Cache-Control "public, no-transform";
        add_header Access-Control-Allow-Origin "*";
        add_header Access-Control-Allow-Methods "GET, OPTIONS";
    }

    # Otimização de Gzip para arquivos CSS e JS
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml;
    gzip_min_length 1000;
}
